<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>gerenciadorescritorio.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="gerenciadorescritorio.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="itext" Version="9.7.0" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>

</Project>